[project]
name = "self-halt"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "itables>=2.6.1",
    "jupyter>=1.1.1",
    "matplotlib>=3.10.8",
    "pandas>=2.3.3",
    "pyyaml>=6.0.3",
]
